#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

def options(argv)
  o = {}
  a = []

  while argv.any?
    x = argv.shift

    if x.start_with?('--')
      k = x[2..-1].downcase
      v = argv.shift

      v = v.to_i if v =~ /^\d+$/

      o[k] = v
    else
      a << x
    end
  end

  [o, a]
end

Dir.mkdir('data') unless File.directory?('data')

opts, argv = options(ARGV.dup)

filename = argv.shift
json = open(filename, 'r').read
data = JSON.parse(json)

file_number = 0

name = File.basename(filename, '.en.json3')

md = File.open("#{name}.txt", 'w')

data['events'].each do |event|
  next unless event.key?('segs')
  next unless event.include?('dDurationMs')

  d = event['dDurationMs']
  next if d < 1000 # Too short an utterance cannot be processed

  start_ms = event['tStartMs']
  end_ms   = start_ms + d
  words = event['segs'].map { |s| s['utf8'] }.join(' ').gsub('\n', ' ').gsub(/\s+/, ' ').strip

  next if words == ''
  next if words.include?('[') # This utterance includes a swear word or music or something
  next unless words.include?(' ') # Ignore 1 word utterances

  file_number += 1

  fn = "#{name}_%05d" % file_number

  system("./segment #{name}.wav #{start_ms} #{end_ms} data/#{fn}.wav")
  md.puts "#{fn}|0|#{words}"
  puts "#{fn}|0|#{words}"

  break if opts['limit'] && opts['limit'] <= file_number
end
md.close
